# Generated by Django 3.0.8 on 2020-11-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='id_name',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id_name',
            new_name='id',
        ),
    ]
