# Generated by Django 3.0.8 on 2020-11-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.AddField(
            model_name='card',
            name='prerequisites',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
