# Generated by Django 3.1.4 on 2020-12-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='cards'),
        ),
        migrations.AlterField(
            model_name='card',
            name='prerequisites',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
