# Generated by Django 3.1.2 on 2020-11-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201116_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='prerequisites',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
