# Generated by Django 3.0.8 on 2020-11-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201103_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.AddField(
            model_name='card',
            name='id_name',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='id_name',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
