# Generated by Django 3.1.2 on 2020-11-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201111_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='card',
            name='prerequisites',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
